# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

dist: precise

matrix:
  include:
  - env: GO_VERSION=1.11.13

before_install:
- pwd
- export GOROOT=$HOME/.go
- mkdir -p $GOROOT
- export GOPATH=$HOME
- mkdir -p $GOPATH/src/github.com/GoogleCloudPlatform
- cd .. && mv appengine-sidecars-docker $GOPATH/src/github.com/GoogleCloudPlatform
- cd $GOPATH/src/github.com/GoogleCloudPlatform/appengine-sidecars-docker

install:
- testing/docker_install_deps.bash
- export PATH=$GOROOT/bin:$PATH

script:
- testing/all.bash
